project_id = "rjjkbnglizodcsjtqicq"

[functions.create-bankkonto-api]
verify_jwt = false

[functions.generate-rechnung-pdf]
verify_jwt = true

[functions.generate-rechnung-docx]
verify_jwt = true

[functions.generate-kaufvertrag-pdf]
verify_jwt = true

[functions.generate-kaufvertrag-docx]
verify_jwt = true

[functions.generate-treuhandvertrag-pdf]
verify_jwt = true

[functions.generate-treuhandvertrag-docx]
verify_jwt = true

[functions.amount-to-words]
verify_jwt = true

[functions.create-bestellung-api]
verify_jwt = false