project_id = "rjjkbnglizodcsjtqicq"

[functions.generate-rechnung-pdf]
verify_jwt = true

[functions.generate-rechnung-docx]
verify_jwt = true

[functions.generate-kaufvertrag-pdf]
verify_jwt = true

[functions.generate-kaufvertrag-docx]
verify_jwt = true

[functions.amount-to-words]
verify_jwt = true