// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rjjkbnglizodcsjtqicq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJqamtibmdsaXpvZGNzanRxaWNxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5Mjg5MjIsImV4cCI6MjA2ODUwNDkyMn0.Ld3uHuHqkxe0aB1T_BKpy4kqSPwB9ZnWywT8bUrCmDg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});